kind: Namespace
apiVersion: v1
metadata:
  name: cloudbees-core
  labels:
    name: cloudbees-core
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oc-casc-bundle
  namespace: cloudbees-core
data:
  bundle.yaml: |
    id: "oc-casc-bundle"
    version: "5"
    apiVersion: "1"
    description: "CasC for OC bundle"
    jcasc:
      - "jenkins.yaml"
  jenkins.yaml: |
    jenkins:
      systemMessage: "Operations Center configured using CasC."
      numExecutors: 0
    cloudBeesCasCServer:
      visibility: true (2)
    masterProvisioning:
      kubernetes:
        cpus: "3.0"
        disk: 50
        fsGroup: "4321"
        javaOptions: "-XshowSettings:vm -XX:+AlwaysPreTouch -XX:+UseG1GC\
          \ -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication\
          \ -Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.DNSMultiCast.disabled=true"
        livenessInitialDelaySeconds: 300
        livenessPeriodSeconds: 10
        livenessTimeoutSeconds: 10
        memory: 3072
        ratio: 0.7
        readinessFailureThreshold: 100
        readinessInitialDelaySeconds: 30
        readinessTimeoutSeconds: 5
        terminationGracePeriodSeconds: 1200
# In GKE need to get RBAC permissions first with
# kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin [--user=<user-name>|--group=<group-name>]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins
